version: '3.8'
services:
  forge-ui:
    build: .
    container_name: stable-diffusion-forge
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "127.0.0.1:7860:7860"
    volumes:
      - ~/ai/Data/outputs:/mnt/outputs
      - ~/ai/Data/checkpoints:/app/forge/models/Stable-diffusion
      - ~/ai/Data/loras:/app/forge/models/Lora
    # NixOS GPU device assignment
    devices:
      - nvidia.com/gpu=all
    shm_size: '8gb'
    dns:
      - 1.1.1.1
      - 8.8.8.8
    dns_search: []
    dns_opt:
      - ndots:0
      - attempts:3
